/**
 * Resource type visual configuration for the AWS resource graph.
 * Maps resource types to their display color, label, and icon filename.
 */

export interface ResourceTypeConfig {
    "color": string;
    "label": string;
    "icon": string;
}

export const RESOURCE_TYPE_MAP: Record<string, ResourceTypeConfig> = {
    "region": {"color": "#232F3E",
        "label": "Region",
        "icon": "region.svg"},
    "vpc": {"color": "#8C4FFF",
        "label": "VPC",
        "icon": "vpc.svg"},
    "subnet": {"color": "#8C4FFF",
        "label": "Subnet",
        "icon": "subnet.svg"},
    "securitygroup": {"color": "#DD344C",
        "label": "Security Group",
        "icon": "securitygroup.svg"},
    "internetgateway": {"color": "#8C4FFF",
        "label": "Internet Gateway",
        "icon": "internetgateway.svg"},
    "natgateway": {"color": "#8C4FFF",
        "label": "NAT Gateway",
        "icon": "natgateway.svg"},
    "networkinterface": {"color": "#8C4FFF",
        "label": "Network Interface",
        "icon": "networkinterface.svg"},
    "routetable": {"color": "#8C4FFF",
        "label": "Route Table",
        "icon": "routetable.svg"},
    "vpcendpoint": {"color": "#8C4FFF",
        "label": "VPC Endpoint",
        "icon": "vpcendpoint.svg"},
    "vpcpeering": {"color": "#8C4FFF",
        "label": "VPC Peering",
        "icon": "vpcpeering.svg"},
    "flowlog": {"color": "#8C4FFF",
        "label": "Flow Log",
        "icon": "flowlog.svg"},
    "networkacl": {"color": "#8C4FFF",
        "label": "Network ACL",
        "icon": "networkacl.svg"},
    "dhcpoptions": {"color": "#8C4FFF",
        "label": "DHCP Options",
        "icon": "dhcpoptions.svg"},
    "prefixlist": {"color": "#8C4FFF",
        "label": "Prefix List",
        "icon": "prefixlist.svg"},
    "transitgateway": {"color": "#8C4FFF",
        "label": "Transit Gateway",
        "icon": "transitgateway.svg"},
    "localgateway": {"color": "#8C4FFF",
        "label": "Local Gateway",
        "icon": "localgateway.svg"},
    "elasticip": {"color": "#8C4FFF",
        "label": "Elastic IP",
        "icon": "elasticip.svg"},
    "instanceconnectendpoint": {"color": "#8C4FFF",
        "label": "Instance Connect EP",
        "icon": "vpcendpoint.svg"},
    "instance": {"color": "#ED7100",
        "label": "EC2 Instance",
        "icon": "instance.svg"},
    "ami": {"color": "#ED7100",
        "label": "AMI",
        "icon": "ami.svg"},
    "launchtemplate": {"color": "#ED7100",
        "label": "Launch Template",
        "icon": "launchtemplate.svg"},
    "keypair": {"color": "#ED7100",
        "label": "Key Pair",
        "icon": "keypair.svg"},
    "volume": {"color": "#3B48CC",
        "label": "EBS Volume",
        "icon": "volume.svg"},
    "snapshot": {"color": "#3B48CC",
        "label": "EBS Snapshot",
        "icon": "snapshot.svg"},
    "s3bucket": {"color": "#3B48CC",
        "label": "S3 Bucket",
        "icon": "s3bucket.svg"},
    "lambdafunction": {"color": "#ED7100",
        "label": "Lambda Function",
        "icon": "lambdafunction.svg"},
    "lambdaalias": {"color": "#ED7100",
        "label": "Lambda Alias",
        "icon": "lambdafunction.svg"},
    "lambdalayer": {"color": "#ED7100",
        "label": "Lambda Layer",
        "icon": "lambda.svg"},
    "functionurl": {"color": "#ED7100",
        "label": "Function URL",
        "icon": "lambdafunction.svg"},
    "provisionedconcurrency": {"color": "#ED7100",
        "label": "Provisioned Concurrency",
        "icon": "lambdafunction.svg"},
    "eventsourcemapping": {"color": "#ED7100",
        "label": "Event Source Mapping",
        "icon": "lambda.svg"},
    "role": {"color": "#DD344C",
        "label": "IAM Role",
        "icon": "role.svg"},
    "user": {"color": "#DD344C",
        "label": "IAM User",
        "icon": "user.svg"},
    "policy": {"color": "#DD344C",
        "label": "IAM Policy",
        "icon": "policy.svg"},
    "group": {"color": "#DD344C",
        "label": "IAM Group",
        "icon": "group.svg"},
    "instanceprofile": {"color": "#DD344C",
        "label": "Instance Profile",
        "icon": "instanceprofile.svg"},
    "mfadevice": {"color": "#DD344C",
        "label": "MFA Device",
        "icon": "mfadevice.svg"},
    "virtualmfadevice": {"color": "#DD344C",
        "label": "Virtual MFA",
        "icon": "mfadevice.svg"},
    "accesskey": {"color": "#DD344C",
        "label": "Access Key",
        "icon": "accesskey.svg"},
    "sshpublickey": {"color": "#DD344C",
        "label": "SSH Public Key",
        "icon": "sshpublickey.svg"},
    "servercertificate": {"color": "#DD344C",
        "label": "Server Certificate",
        "icon": "servercertificate.svg"},
    "distribution": {"color": "#8C4FFF",
        "label": "CloudFront Distribution",
        "icon": "distribution.svg"},
    "cloudfrontfunction": {"color": "#8C4FFF",
        "label": "CloudFront Function",
        "icon": "cloudfrontfunction.svg"},
    "originaccesscontrol": {"color": "#8C4FFF",
        "label": "Origin Access Control",
        "icon": "originaccesscontrol.svg"},
    "loggroup": {"color": "#ED7100",
        "label": "Log Group",
        "icon": "loggroup.svg"},
    "alarm": {"color": "#ED7100",
        "label": "CloudWatch Alarm",
        "icon": "alarm.svg"}
};

const DEFAULT_CONFIG: ResourceTypeConfig = {"color": "#232F3E",
    "label": "Unknown",
    "icon": "region.svg"};

export function getResourceTypeConfig (type: string): ResourceTypeConfig {

    return RESOURCE_TYPE_MAP[type] ?? DEFAULT_CONFIG;

}
